### ISSUE TITLE
Update Cocoapods to new version

### ISSUE THREAD

**Issue by lfarah** [lucoceano/Pager#8]
## Changes:

Fixes #6 - `Scrolling tabs quickly using swipe gestures will lead to a crash.`
## Todo:
- [x] update .podspec with new version
- [x] create new tag on Git
- [x] push to CocoaPods with `pod trunk push [Pager.podspec]`

**Comment by lfarah** [comment]
Hey @lucoceano, I need you to update your Trunk with my account:
[CocoaPods - Adding other people as contributors](https://guides.cocoapods.org/making/getting-setup-with-trunk#adding-other-people-as-contributors)

**Comment by lucoceano** [comment]
@lfarah sorry man, took me forever to see this! I've just added.

**Comment by lfarah** [comment]
It's ok.... 😄
